-- Клауд — схема каталога частных объявлений (PostgreSQL).
-- Все временные метки — naive timestamp в UTC: базу и приложение не волнует
-- часовой пояс сервера, наружу отдаётся строка «ГГГГ-ММ-ДД ЧЧ:ММ:СС».
--
-- Файл применяется целиком при каждом старте, поэтому каждая инструкция
-- идемпотентна (IF NOT EXISTS). Новые колонки добавляются в конце файла
-- через ALTER TABLE ... ADD COLUMN IF NOT EXISTS.

-- Единая «текущая метка» вместо datetime('now') из SQLite.
CREATE OR REPLACE FUNCTION now_utc() RETURNS timestamp
  LANGUAGE sql STABLE AS $$ SELECT date_trunc('second', now() AT TIME ZONE 'utc') $$;

CREATE TABLE IF NOT EXISTS users (
  id             INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT      NOT NULL UNIQUE,
  name           TEXT      NOT NULL,
  phone          TEXT      NOT NULL UNIQUE,
  email          TEXT,
  password_hash  TEXT      NOT NULL,
  city           TEXT      NOT NULL DEFAULT 'Москва',
  type           TEXT      NOT NULL DEFAULT 'Частное лицо',
  bio            TEXT      NOT NULL DEFAULT '',
  rating         REAL      NOT NULL DEFAULT 5.0,
  reviews_count  INTEGER   NOT NULL DEFAULT 0,
  deals          INTEGER   NOT NULL DEFAULT 0,
  notify_deals   INTEGER   NOT NULL DEFAULT 1,
  notify_journal INTEGER   NOT NULL DEFAULT 0,
  notify_promo   INTEGER   NOT NULL DEFAULT 1,
  email_verified INTEGER   NOT NULL DEFAULT 0,
  -- Номер подтверждён кодом из СМС.
  phone_verified INTEGER   NOT NULL DEFAULT 0,
  role           TEXT      NOT NULL DEFAULT 'user'
                   CHECK (role IN ('user', 'moderator', 'admin')),
  -- Тариф продавца: полка (обычная страница), витрина, издание.
  plan           TEXT      NOT NULL DEFAULT 'shelf'
                   CHECK (plan IN ('shelf', 'storefront', 'edition')),
  plan_until     TIMESTAMP,
  -- Личный редактор издания: аккаунт персонала, закреплённый за издателем.
  editor_id      INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  blocked_at     TIMESTAMP,
  blocked_reason TEXT,
  last_seen_at   TIMESTAMP NOT NULL DEFAULT now_utc(),
  created_at     TIMESTAMP NOT NULL DEFAULT now_utc()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
-- Почта необязательна, но повторяться не должна.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email) WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS categories (
  slug          TEXT    PRIMARY KEY,
  n             TEXT    NOT NULL,
  label         TEXT    NOT NULL,
  blurb         TEXT    NOT NULL DEFAULT '',
  img           TEXT    NOT NULL DEFAULT '',
  display_count INTEGER NOT NULL DEFAULT 0,
  position      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS listings (
  id            INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lot           TEXT      NOT NULL UNIQUE,
  title         TEXT      NOT NULL,
  price         INTEGER   NOT NULL,
  location      TEXT      NOT NULL,
  cond          TEXT      NOT NULL,
  description   TEXT      NOT NULL DEFAULT '',
  cat           TEXT      NOT NULL REFERENCES categories(slug) ON DELETE RESTRICT,
  seller_id     INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge         TEXT,
  status        TEXT      NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'active', 'rejected', 'sold', 'archived')),
  reject_reason TEXT,
  moderated_by  INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  moderated_at  TIMESTAMP,
  sold_at       TIMESTAMP,
  sold_to       INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  views         INTEGER   NOT NULL DEFAULT 0,
  created_at    TIMESTAMP NOT NULL DEFAULT now_utc(),
  updated_at    TIMESTAMP NOT NULL DEFAULT now_utc()
);

CREATE INDEX IF NOT EXISTS idx_listings_cat       ON listings(cat);
CREATE INDEX IF NOT EXISTS idx_listings_seller    ON listings(seller_id);
CREATE INDEX IF NOT EXISTS idx_listings_status    ON listings(status);
CREATE INDEX IF NOT EXISTS idx_listings_price     ON listings(price);
CREATE INDEX IF NOT EXISTS idx_listings_created   ON listings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_listings_moderated ON listings(moderated_at DESC);
CREATE INDEX IF NOT EXISTS idx_listings_sold      ON listings(sold_at DESC);

CREATE TABLE IF NOT EXISTS listing_images (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  url        TEXT    NOT NULL,
  position   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_images_listing ON listing_images(listing_id, position);

CREATE TABLE IF NOT EXISTS favorites (
  user_id    INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id INTEGER   NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now_utc(),
  PRIMARY KEY (user_id, listing_id)
);

CREATE TABLE IF NOT EXISTS threads (
  id         INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id INTEGER   NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  buyer_id   INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seller_id  INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now_utc(),
  updated_at TIMESTAMP NOT NULL DEFAULT now_utc(),
  UNIQUE (listing_id, buyer_id)
);

CREATE INDEX IF NOT EXISTS idx_threads_buyer  ON threads(buyer_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_threads_seller ON threads(seller_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS messages (
  id         INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id  INTEGER   NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  sender_id  INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text       TEXT      NOT NULL,
  read_at    TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now_utc()
);

CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id, created_at);

CREATE TABLE IF NOT EXISTS articles (
  slug         TEXT      PRIMARY KEY,
  rubric       TEXT      NOT NULL,
  title        TEXT      NOT NULL,
  excerpt      TEXT      NOT NULL DEFAULT '',
  author       TEXT      NOT NULL DEFAULT 'Редакция',
  author_id    INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  date         TEXT      NOT NULL,
  read         TEXT      NOT NULL DEFAULT '5 мин',
  img          TEXT      NOT NULL DEFAULT '',
  body         TEXT      NOT NULL DEFAULT '[]',
  status       TEXT      NOT NULL DEFAULT 'published'
                 CHECK (status IN ('draft', 'published')),
  published_at TIMESTAMP NOT NULL DEFAULT now_utc(),
  updated_at   TIMESTAMP NOT NULL DEFAULT now_utc()
);

CREATE INDEX IF NOT EXISTS idx_articles_status ON articles(status, published_at DESC);

-- ── Модерация ──

-- Журнал действий модераторов и администраторов: кто, что и почему сделал.
CREATE TABLE IF NOT EXISTS moderation_log (
  id          INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT      NOT NULL,
  target_type TEXT      NOT NULL CHECK (target_type IN ('listing', 'user', 'report', 'article')),
  target_id   INTEGER   NOT NULL,
  reason      TEXT,
  details     TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT now_utc()
);

CREATE INDEX IF NOT EXISTS idx_modlog_created ON moderation_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_modlog_target  ON moderation_log(target_type, target_id);

-- Жалобы покупателей на лоты.
CREATE TABLE IF NOT EXISTS reports (
  id          INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id  INTEGER   NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  reporter_id INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason      TEXT      NOT NULL,
  comment     TEXT      NOT NULL DEFAULT '',
  status      TEXT      NOT NULL DEFAULT 'open'
                CHECK (status IN ('open', 'resolved', 'dismissed')),
  resolved_by INTEGER   REFERENCES users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMP,
  created_at  TIMESTAMP NOT NULL DEFAULT now_utc(),
  UNIQUE (listing_id, reporter_id)
);

CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status, created_at DESC);

-- ── Города ──

-- Справочник городов для выбора в шапке и фильтра каталога.
CREATE TABLE IF NOT EXISTS cities (
  slug     TEXT    PRIMARY KEY,
  name     TEXT    NOT NULL,
  region   TEXT    NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 0
);

-- ── Отзывы о сделках ──

-- Один отзыв на пару «лот + автор»: покупатель оценивает продавца после сделки.
CREATE TABLE IF NOT EXISTS reviews (
  id           INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id   INTEGER   NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  author_id    INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_id    INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating       INTEGER   NOT NULL CHECK (rating BETWEEN 1 AND 5),
  deal_success INTEGER   NOT NULL DEFAULT 1,
  text         TEXT      NOT NULL DEFAULT '',
  created_at   TIMESTAMP NOT NULL DEFAULT now_utc(),
  UNIQUE (listing_id, author_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_target ON reviews(target_id, created_at DESC);

-- ── Коды подтверждения ──
-- Один действующий код на номер: новый запрос перезаписывает прежний.
-- Сам код не храним, только хеш — как и пароль.
CREATE TABLE IF NOT EXISTS phone_codes (
  phone      TEXT      PRIMARY KEY,
  code_hash  TEXT      NOT NULL,
  purpose    TEXT      NOT NULL CHECK (purpose IN ('register', 'login')),
  attempts   INTEGER   NOT NULL DEFAULT 0,
  sent_at    TIMESTAMP NOT NULL DEFAULT now_utc(),
  expires_at TIMESTAMP NOT NULL
);

-- ── Вход через соцсети ──
-- Связь аккаунта площадки с профилем ВКонтакте или Mail.ru.
CREATE TABLE IF NOT EXISTS social_accounts (
  provider    TEXT      NOT NULL CHECK (provider IN ('vk', 'mailru')),
  external_id TEXT      NOT NULL,
  user_id     INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email       TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT now_utc(),
  PRIMARY KEY (provider, external_id)
);

CREATE INDEX IF NOT EXISTS idx_social_user ON social_accounts(user_id);

-- ── Витрина продавца ──
-- Оформление магазина на тарифах «Витрина» и «Издание». Строка появляется,
-- когда продавец впервые открывает настройку витрины.
CREATE TABLE IF NOT EXISTS storefronts (
  user_id    INTEGER   PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  brand      TEXT      NOT NULL DEFAULT '',
  tagline    TEXT      NOT NULL DEFAULT '',
  cover      TEXT      NOT NULL DEFAULT '',
  about      TEXT      NOT NULL DEFAULT '',
  hours      TEXT      NOT NULL DEFAULT '',
  delivery   TEXT      NOT NULL DEFAULT '',
  warranty   TEXT      NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT now_utc()
);

-- Ссылки-чипы на обложке магазина.
CREATE TABLE IF NOT EXISTS storefront_links (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  network  TEXT    NOT NULL,
  handle   TEXT    NOT NULL DEFAULT '',
  url      TEXT    NOT NULL,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sf_links_user ON storefront_links(user_id, position);

-- Разделы витрины (тариф «Издание»): свои названия рубрик поверх категорий.
CREATE TABLE IF NOT EXISTS storefront_sections (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title    TEXT    NOT NULL,
  blurb    TEXT    NOT NULL DEFAULT '',
  cat      TEXT    REFERENCES categories(slug) ON DELETE SET NULL,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sf_sections_user ON storefront_sections(user_id, position);

-- ── Издательский дом ──
-- Тариф «Издание»: несколько витрин под одной обложкой и своя полоса
-- на главной. Издатель — это владелец тарифа, витрины — другие продавцы.
CREATE TABLE IF NOT EXISTS publisher_shops (
  publisher_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  member_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  position     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (publisher_id, member_id)
);

-- Витрина принадлежит только одному изданию.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pub_member ON publisher_shops(member_id);

-- Приглашения витрин в издательский дом: витрина входит в дом только после
-- согласия своего владельца.
CREATE TABLE IF NOT EXISTS publisher_invites (
  publisher_id INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  member_id    INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   TIMESTAMP NOT NULL DEFAULT now_utc(),
  PRIMARY KEY (publisher_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_pub_invites_member ON publisher_invites(member_id);

-- Подборка «Выбор издания» — она же полоса на главной.
CREATE TABLE IF NOT EXISTS publisher_picks (
  publisher_id INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id   INTEGER   NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  position     INTEGER   NOT NULL DEFAULT 0,
  updated_at   TIMESTAMP NOT NULL DEFAULT now_utc(),
  PRIMARY KEY (publisher_id, listing_id)
);

CREATE INDEX IF NOT EXISTS idx_pub_picks ON publisher_picks(publisher_id, position);

-- ── Справка ──
-- Разделы и вопросы страницы «Помощь». Контент лежит в базе, а не в вёрстке.
CREATE TABLE IF NOT EXISTS help_topics (
  slug     TEXT    PRIMARY KEY,
  n        TEXT    NOT NULL,
  title    TEXT    NOT NULL,
  blurb    TEXT    NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS faq (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT    NOT NULL,
  question TEXT    NOT NULL,
  answer   TEXT    NOT NULL,
  position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_faq_category ON faq(category, position);

-- ── О проекте ──
-- Принципы и вехи страницы «О проекте». `kind` разделяет два вида блоков.
CREATE TABLE IF NOT EXISTS about_blocks (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind     TEXT    NOT NULL CHECK (kind IN ('principle', 'milestone')),
  label    TEXT    NOT NULL,
  title    TEXT    NOT NULL,
  text     TEXT    NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_about_kind ON about_blocks(kind, position);

-- ── Дозаполнение схемы ──
-- Изменения для баз, созданных предыдущими версиями. Postgres умеет
-- ADD COLUMN IF NOT EXISTS, поэтому отдельный механизм миграций не нужен:
-- дописывайте инструкции сюда, они выполняются при каждом старте.

ALTER TABLE users ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'shelf';
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_until TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_users_plan ON users(plan);
ALTER TABLE users ADD COLUMN IF NOT EXISTS editor_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified INTEGER NOT NULL DEFAULT 0;
